/*
* generated by Xtext
*/
package org.xtext.bhdrkn.function.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FunctionAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/bhdrkn/function/parser/antlr/internal/InternalFunction.tokens");
	}
}
