/*
 * generated by Xtext
 */
package org.xtext.bhdrkn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FouroperationUiModule extends org.xtext.bhdrkn.ui.AbstractFouroperationUiModule {
	public FouroperationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
