/*
* generated by Xtext
*/
package org.xtext.bhdrkn.ui.contentassist;

import org.xtext.bhdrkn.ui.contentassist.AbstractFouroperationProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FouroperationProposalProvider extends AbstractFouroperationProposalProvider {

}
