/*
* generated by Xtext
*/
package org.xtext.bhdrkn.function.ui.contentassist;

import org.xtext.bhdrkn.function.ui.contentassist.AbstractFunctionProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FunctionProposalProvider extends AbstractFunctionProposalProvider {

}
