/*
* generated by Xtext
*/
package org.xtext.bhdrkn.function.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class FunctionTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
