/*
* generated by Xtext
*/

package org.xtext.bhdrkn.function.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class FunctionGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class FUNCFileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FUNCFile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFunctionsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFunctionsFunctionsParserRuleCall_0_0 = (RuleCall)cFunctionsAssignment_0.eContents().get(0);
		private final Assignment cCallsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCallsCallsParserRuleCall_1_0 = (RuleCall)cCallsAssignment_1.eContents().get(0);
		
		//FUNCFile:
		//	functions=Functions calls=Calls;
		public ParserRule getRule() { return rule; }

		//functions=Functions calls=Calls
		public Group getGroup() { return cGroup; }

		//functions=Functions
		public Assignment getFunctionsAssignment_0() { return cFunctionsAssignment_0; }

		//Functions
		public RuleCall getFunctionsFunctionsParserRuleCall_0_0() { return cFunctionsFunctionsParserRuleCall_0_0; }

		//calls=Calls
		public Assignment getCallsAssignment_1() { return cCallsAssignment_1; }

		//Calls
		public RuleCall getCallsCallsParserRuleCall_1_0() { return cCallsCallsParserRuleCall_1_0; }
	}

	public class FunctionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Functions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFUNCTIONSKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFunctionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFunctionsFunctionParserRuleCall_1_0 = (RuleCall)cFunctionsAssignment_1.eContents().get(0);
		private final Keyword cFUNCTIONSKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Functions:
		//	"[FUNCTIONS]" functions+=Function* "[/FUNCTIONS]";
		public ParserRule getRule() { return rule; }

		//"[FUNCTIONS]" functions+=Function* "[/FUNCTIONS]"
		public Group getGroup() { return cGroup; }

		//"[FUNCTIONS]"
		public Keyword getFUNCTIONSKeyword_0() { return cFUNCTIONSKeyword_0; }

		//functions+=Function*
		public Assignment getFunctionsAssignment_1() { return cFunctionsAssignment_1; }

		//Function
		public RuleCall getFunctionsFunctionParserRuleCall_1_0() { return cFunctionsFunctionParserRuleCall_1_0; }

		//"[/FUNCTIONS]"
		public Keyword getFUNCTIONSKeyword_2() { return cFUNCTIONSKeyword_2; }
	}

	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFunctionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Function:
		//	"function" name=ID;
		public ParserRule getRule() { return rule; }

		//"function" name=ID
		public Group getGroup() { return cGroup; }

		//"function"
		public Keyword getFunctionKeyword_0() { return cFunctionKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class CallsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Calls");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCALLSKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCallsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCallsCallParserRuleCall_1_0 = (RuleCall)cCallsAssignment_1.eContents().get(0);
		private final Keyword cCALLSKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Calls:
		//	"[CALLS]" calls+=Call* "[/CALLS]";
		public ParserRule getRule() { return rule; }

		//"[CALLS]" calls+=Call* "[/CALLS]"
		public Group getGroup() { return cGroup; }

		//"[CALLS]"
		public Keyword getCALLSKeyword_0() { return cCALLSKeyword_0; }

		//calls+=Call*
		public Assignment getCallsAssignment_1() { return cCallsAssignment_1; }

		//Call
		public RuleCall getCallsCallParserRuleCall_1_0() { return cCallsCallParserRuleCall_1_0; }

		//"[/CALLS]"
		public Keyword getCALLSKeyword_2() { return cCALLSKeyword_2; }
	}

	public class CallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Call");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cNameFunctionCrossReference_1_0 = (CrossReference)cNameAssignment_1.eContents().get(0);
		private final RuleCall cNameFunctionIDTerminalRuleCall_1_0_1 = (RuleCall)cNameFunctionCrossReference_1_0.eContents().get(1);
		
		//Call:
		//	"call" name=[Function];
		public ParserRule getRule() { return rule; }

		//"call" name=[Function]
		public Group getGroup() { return cGroup; }

		//"call"
		public Keyword getCallKeyword_0() { return cCallKeyword_0; }

		//name=[Function]
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//[Function]
		public CrossReference getNameFunctionCrossReference_1_0() { return cNameFunctionCrossReference_1_0; }

		//ID
		public RuleCall getNameFunctionIDTerminalRuleCall_1_0_1() { return cNameFunctionIDTerminalRuleCall_1_0_1; }
	}
	
	
	private FUNCFileElements pFUNCFile;
	private FunctionsElements pFunctions;
	private FunctionElements pFunction;
	private CallsElements pCalls;
	private CallElements pCall;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public FunctionGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//FUNCFile:
	//	functions=Functions calls=Calls;
	public FUNCFileElements getFUNCFileAccess() {
		return (pFUNCFile != null) ? pFUNCFile : (pFUNCFile = new FUNCFileElements());
	}
	
	public ParserRule getFUNCFileRule() {
		return getFUNCFileAccess().getRule();
	}

	//Functions:
	//	"[FUNCTIONS]" functions+=Function* "[/FUNCTIONS]";
	public FunctionsElements getFunctionsAccess() {
		return (pFunctions != null) ? pFunctions : (pFunctions = new FunctionsElements());
	}
	
	public ParserRule getFunctionsRule() {
		return getFunctionsAccess().getRule();
	}

	//Function:
	//	"function" name=ID;
	public FunctionElements getFunctionAccess() {
		return (pFunction != null) ? pFunction : (pFunction = new FunctionElements());
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}

	//Calls:
	//	"[CALLS]" calls+=Call* "[/CALLS]";
	public CallsElements getCallsAccess() {
		return (pCalls != null) ? pCalls : (pCalls = new CallsElements());
	}
	
	public ParserRule getCallsRule() {
		return getCallsAccess().getRule();
	}

	//Call:
	//	"call" name=[Function];
	public CallElements getCallAccess() {
		return (pCall != null) ? pCall : (pCall = new CallElements());
	}
	
	public ParserRule getCallRule() {
		return getCallAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" | "n" |
	//	"f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
