
/*
 * generated by Xtext
 */
 
package org.xtext.bhdrkn.function.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class FunctionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.xtext.bhdrkn.function.ui.internal.FunctionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.xtext.bhdrkn.function.ui.internal.FunctionActivator.getInstance().getInjector("org.xtext.bhdrkn.function.Function");
	}
	
}
