/*
 * generated by Xtext
 */
package org.xtext.bhdrkn.function;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FunctionRuntimeModule extends org.xtext.bhdrkn.function.AbstractFunctionRuntimeModule {

}
