
/*
 * generated by Xtext
 */
 
package org.xtext.bhdrkn.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class FouroperationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.xtext.bhdrkn.ui.internal.FouroperationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.xtext.bhdrkn.ui.internal.FouroperationActivator.getInstance().getInjector("org.xtext.bhdrkn.Fouroperation");
	}
	
}
