/*
 * generated by Xtext
 */
package org.xtext.bhdrkn;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FouroperationRuntimeModule extends org.xtext.bhdrkn.AbstractFouroperationRuntimeModule {

}
